export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';
export const LOGIN_CURRENT_USER = 'LOGIN_CURRENT_USER';
export const REGISTER_CURRENT_USER = 'REGISTER_CURRENT_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const UPDATE_CONTACT_DETAILS_START = 'UPDATE_CONTACT_DETAILS_START';
export const UPDATE_CONTACT_DETAILS_SUCCESS = 'UPDATE_CONTACT_DETAILS_SUCCESS';
export const UPDATE_CONTACT_DETAILS_FAIL = 'UPDATE_CONTACT_DETAILS_FAIL';
export const FETCH_CONTACT_DETAILS = 'FETCH_CONTACT_DETAILS';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const CLEAR_FAVORITES = 'CLEAR_FAVORITES';
export const FETCH_FAVORITES_START = 'FETCH_FAVORITES_START';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_FAIL = 'FETCH_FAVORITES_FAIL';

export const TOGGLE_ACCOUNT_DETAILS = 'TOGGLE_ACCOUNT_DETAILS';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';
export const CLEAR_ALL_CART = 'CLEAR_ALL_CART';
export const TOGGLE_CART_MENU = 'TOGGLE_CART_MENU';

export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const CLEAR_ALL_PURCHASES = 'CLEAR_ALL_PURCHASES';

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const CLEAR_ORDER_HISTORY = 'CLEAR_ORDER_HISTORY';
