export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';
export const LOGIN_CURRENT_USER = 'LOGIN_CURRENT_USER';
export const REGISTER_CURRENT_USER = 'REGISTER_CURRENT_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const TOGGLE_ACCOUNT_DETAILS = 'TOGGLE_ACCOUNT_DETAILS';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const TOGGLE_CART_MENU = 'TOGGLE_CART_MENU';
